// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nybzfxjtafdpgxndjukw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im55YnpmeGp0YWZkcGd4bmRqdWt3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzNzQzODEsImV4cCI6MjA1Njk1MDM4MX0.tTlCt4euc-81bh3BD22AbP360VvPDahVQzAPR28Jd6k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);